# specify base image from dockerhub
FROM node:14-alpine3.10

LABEL version="1.0"
LABEL description="Development image for Redspher calculator Front"

# workdir of the container
# all commands executed are relative to this directory
WORKDIR /app

COPY ["package.json","package-lock.json*", "./"]

# Install dependencies 
RUN npm install

COPY . .

# use EXPOSE command to have our port mapped by the docker daemon
EXPOSE 4000

# default dev command
CMD [ "npm", "run", "start" ]